version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}"
    restart: "always"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/html:rw
      - ${APACHE_CONFIG-./docker/apache/000-default.conf}:/etc/apache2/sites-enabled/000-default.conf
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${SSL_DIR-./docker/config/ssl}:/etc/apache2/ssl/
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./docker/logs/apache2}:/var/log/apache2
      - ${XDEBUG_LOG_DIR-./docker/logs/xdebug}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
