name: Check PHPLint (E2E|CI)

on:
  [push]

permissions:
  contents: read

jobs:
  phplint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2']
    steps:
        - uses: actions/checkout@v1
        - uses: michaelw90/PHP-Lint@master