name: Merge All Pull Requests to Beta

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight (UTC)

jobs:
  merge_prs_to_beta:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: |
        git config --global user.email "admin@olfant.com"
        git config --global user.name "Olfant Corporation"

    - name: Fetch branches and PRs
      run: |
        git fetch origin
        git fetch origin '+refs/pull/*/head:refs/remotes/origin/pr/*'

    - name: Merge all open PRs to beta
      run: |
        git checkout beta
        for pr in $(git branch -r | grep 'origin/pr/' | sed 's/origin\///'); do
          git merge --no-edit "$pr"
        done

    - name: Push changes to beta branch
      run: git push origin beta
